name: Deploy To EC2 Triggered by push on release-dev branch

on:
  push:
    branches:
      - release-dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml

      - name: OAuth2 연동을 위한 환경변수 만들기
        run : echo "${{secrets.APPLICATION_OAUTH_PROPERTIES}}" > ./src/main/resources/application-oauth.properties

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드 된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: project.jar
          target: /home/ubuntu/hongik-mentor/tobe


      - name: SSH로 EC2 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/hongik-mentor/current
            mkdir /home/ubuntu/hongik-mentor/current
            mv /home/ubuntu/hongik-mentor/tobe/project.jar /home/ubuntu/hongik-mentor/current/project.jar
            cd /home/ubuntu/hongik-mentor/current
            sudo fuser -k -n tcp 8080 || true
            nohup  java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/hongik-mentor/tobe
              
